
export const DONORSPEAKS_LOADING = "DONORSPEAKS_LOADING";
export const DONORSPEAKS_FAILED = "DONORSPEAKS_FAILED";
export const ADD_DONORSPEAKS = "ADD_DONORSPEAKS";
export const ADD_DONORSPEAK = "ADD_DONORSPEAK";
export const DELETE_DONORSPEAK = "DELETE_DONORSPEAK";

export const NGOBLOGS_LOADING = "NGOBLOGS_LOADING";
export const NGOBLOGS_FAILED = "NGOBLOGS_FAILED";
export const ADD_NGOBLOGS = "ADD_NGOBLOGS";
export const ADD_NGOBLOG = "ADD_NGOBLOG";
export const DELETE_NGOBLOG = "DELETE_NGOBLOG";


//user actions

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";