//DONOR SPEAKS

export const DONORSPEAKS_LOADING = 'DONORSPEAKS_LOADING';
export const DONORSPEAKS_FAILED = 'DONORSPEAKS_FAILED';
export const ADD_DONORSPEAKS = 'ADD_DONORSPEAKS';
export const ADD_DONORSPEAK = 'ADD_DONORSPEAK';
export const DELETE_DONORSPEAK = 'DELETE_DONORSPEAK';

//NGO BLOGS
export const NGOBLOGS_LOADING = 'NGOBLOGS_LOADING';
export const NGOBLOGS_FAILED = 'NGOBLOGS_FAILED';
export const ADD_NGOBLOGS = 'ADD_NGOBLOGS';
export const ADD_NGOBLOG = 'ADD_NGOBLOG';
export const FETCH_NGOBLOG = 'FETCH_NGOBLOG';
export const DELETE_NGOBLOG = 'DELETE_NGOBLOG';

//NGO BENEFICIARIES
export const NGOBENEFICIARIES_LOADING = 'NGOBENEFICIARIES_LOADING';
export const NGOBENEFICIARIES_FAILED = 'NGOBENEFICIARIES_FAILED';
export const ADD_NGOBENEFICIARIES = 'ADD_NGOBENEFICIARIES';
export const ADD_NGOBENEFICIARY = 'ADD_NGOBENEFICIARY';
export const DELETE_NGOBENEFICIARY = 'DELETE_NGOBENEFICIARY';

//MEDICINES

export const MEDICINES_LOADING = 'MEDICINES_LOADING';
export const MEDICINES_FAILED = 'MEDICINES_FAILED';
export const ADD_MEDICINES = 'ADD_MEDICINES';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';

//user actions

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

//USER lists
export const USERLISTS_LOADING = 'USERLISTS_LOADING';
export const USERLISTS_FAILED = 'USERLISTS_FAILED';
export const ADD_USERLISTS = 'ADD_USERLISTS';
export const DELETE_USERLIST = 'DELETE_USERLIST';
export const ADD_USERLIST = 'ADD_USERLIST';
